input_shape_voxels: [32, 32, 32]
eval_input_shape_voxels: [120, 120, 120]
num_iterations: 50_000
checkpoint_interval: 1_000
snapshot_interval: 1_000
warmup: 10_000
batch_size: 6
checkpoint_dir: "/nrs/funke/pattonw/op_experiments/arlo_barcodes/checkpoints"
snapshot_container: "/nrs/funke/pattonw/op_experiments/arlo_barcodes/snapshots.zarr"
validation_container: "/nrs/funke/pattonw/op_experiments/arlo_barcodes/validations.zarr"
loss_file: "/nrs/funke/pattonw/op_experiments/arlo_barcodes/losses.csv"
val_file: "/nrs/funke/pattonw/op_experiments/arlo_barcodes/validations.csv"
learning_rate: 0.0001
num_workers: 10
data_config_file: "configs/data/arlo_barcodes.yaml"
architecture_config_file: "configs/architecture/dense_wide_shallow.yaml"