input_shape_voxels: [200, 200]
eval_input_shape_voxels: [512, 512]
num_iterations: 100_000
checkpoint_interval: 1000
snapshot_interval: 1000
warmup: 1000
batch_size: 6
base_dir: "experiments/opcare-ai4life-unet"
learning_rate: 0.0001
num_workers: 4
pred_delta: True
data_config:
  datasets:
    - "data/noisy.tiff"
  neighborhood:
    - [21, 0]
    - [0, 21]
    - [-21, 0]
    - [0, -21]
architecture_config:
  model_type: "unet"
  in_channels: 1
  num_fmaps: 16
  fmap_inc_factor: 4
  num_fmaps_out: 4
  down_sample_factors: [[2, 2], [2, 2]]
