input_shape_voxels: [256, 256]
eval_input_shape_voxels: [512, 512]
num_iterations: 10_000
checkpoint_interval: 100
snapshot_interval: 100
warmup: 100
batch_size: 6
base_dir: "experiments/opcare-ai4life-small"
learning_rate: 0.0001
num_workers: 4
data_config:
  datasets:
    - "data/noisy.tiff"
  neighborhood:
    - [5, 0]
architecture_config:
  model_type: "dense"
  raw_input_channels: 1
  n_output_channels: 1
  num_init_features: 12
  num_embeddings: 8
  growth_rate: 4
  block_config: [4]
  padding: valid
  embeddings: true
