input_shape_voxels: [128, 128]
eval_input_shape_voxels: [512, 512]
num_iterations: 100_000
checkpoint_interval: 1000
snapshot_interval: 1000
warmup: 1000
batch_size: 6
base_dir: "experiments/opcare-ai4life"
learning_rate: 0.0001
num_workers: 10
pred_delta: True
data_config:
  datasets:
    - "data/noisy.tiff"
  neighborhood:
    - [13, 0]
    - [0, 13]
    - [-13, 0]
    - [0, -13]
architecture_config:
  model_type: "dense"
  raw_input_channels: 1
  n_output_channels: 4
  num_init_features: 64
  num_embeddings: 8
  growth_rate: 64
  block_config: [12]
  padding: valid
  embeddings: true
